// P40-MATH-B-P6: native Go AST -> executable, extracted *HEAD case body*.
// Extracts the original Echo routeMethods.find HEAD-case statements verbatim.
// This is a restricted source-level witness, not a whole-Go proof.
package main

import (
 "crypto/sha256"
 "encoding/hex"
 "encoding/json"
 "fmt"
 "go/ast"
 "go/parser"
 "go/printer"
 "go/token"
 "os"
 "strings"
)

type Receipt struct {
 Protocol string `json:"protocol"`
 SourceFile string `json:"source_file"`
 Method string `json:"method"`
 Case string `json:"case"`
 SourceLine int `json:"source_line"`
 StatementSHA256 string `json:"statement_sha256"`
 BodySHA256 string `json:"whole_function_body_sha256"`
 ExtractionAssumptions []string `json:"extraction_assumptions"`
}

func printed(fset *token.FileSet,n ast.Node)string{
 var b strings.Builder
 if err:=printer.Fprint(&b,fset,n);err!=nil{panic(err)}
 return b.String()
}
func main(){
 if len(os.Args)!=4{panic("usage: go run extract_echo_head.go SOURCE/router.go OUT/generated.go OUT/receipt.json")}
 path,outPath,receiptPath:=os.Args[1],os.Args[2],os.Args[3]
 fset:=token.NewFileSet()
 file,err:=parser.ParseFile(fset,path,nil,parser.AllErrors)
 if err!=nil{panic(err)}
 var decl *ast.FuncDecl
 for _,node:=range file.Decls{
  fd,ok:=node.(*ast.FuncDecl);if !ok||fd.Name.Name!="find"||fd.Recv==nil{continue}
  receiver:=strings.TrimPrefix(printed(fset,fd.Recv.List[0].Type),"*")
  if receiver=="routeMethods"{decl=fd;break}
 }
 if decl==nil{panic("original routeMethods.find AST unavailable")}
 var sourceCase *ast.CaseClause
 for _,statement:=range decl.Body.List{
  sw,ok:=statement.(*ast.SwitchStmt);if !ok{continue}
  for _,part:=range sw.Body.List{
   cl,ok:=part.(*ast.CaseClause);if !ok{continue}
   for _,expr:=range cl.List{
    if printed(fset,expr)=="http.MethodHead"{
     if sourceCase!=nil{panic("duplicate HEAD clauses")}
     sourceCase=cl
    }
   }
  }
 }
 if sourceCase==nil||len(sourceCase.Body)!=2{panic("source HEAD branch no longer matches bounded grammar")}
 assign,ok:=sourceCase.Body[0].(*ast.AssignStmt)
 if !ok||len(assign.Lhs)!=1||len(assign.Rhs)!=1||printed(fset,assign.Lhs[0])!="r"||printed(fset,assign.Rhs[0])!="m.head"{panic("HEAD priority assignment grammar drift")}
 cond,ok:=sourceCase.Body[1].(*ast.IfStmt)
 if !ok||printed(fset,cond.Cond)!="autoHandleHEAD && r == nil"||len(cond.Body.List)!=1||cond.Else!=nil{panic("HEAD fallback guard grammar drift")}
 fallback,ok:=cond.Body.List[0].(*ast.AssignStmt)
 if !ok||len(fallback.Lhs)!=1||len(fallback.Rhs)!=1||printed(fset,fallback.Lhs[0])!="r"||printed(fset,fallback.Rhs[0])!="m.get"{panic("GET fallback body grammar drift")}
 extracted:=printed(fset,sourceCase.Body[0])+"\n"+printed(fset,sourceCase.Body[1])
 sum:=sha256.Sum256([]byte(extracted));whole:=sha256.Sum256([]byte(printed(fset,decl.Body)))
 generated:=`// Code generated by P40-P6 from original Echo router.go AST; DO NOT EDIT.
// The two statements in p6ExtractedHead are original Echo HEAD-branch statements.
// All other types and observations are deliberately reduced scaffolding.
package p40p6echo
type p6Method struct { kind string }
type p6Methods struct { head, get *p6Method }
func p6ExtractedHead(hasHead,hasGet,autoHead bool) string {
 var m p6Methods
 if hasHead { m.head=&p6Method{"direct"} }
 if hasGet { m.get=&p6Method{"fallback"} }
 autoHandleHEAD:=autoHead
 var r *p6Method
`+extracted+`
 if r==nil{return "unavailable"}
 return r.kind
}
`
 if err:=os.WriteFile(outPath,[]byte(generated),0644);err!=nil{panic(err)}
 receipt:=Receipt{
  Protocol:"P40_P6_AST_VERBATIM_HEAD_BRANCH_V1",
  SourceFile:path,
  Method:"(*routeMethods).find",
  Case:"http.MethodHead",
  SourceLine:fset.Position(sourceCase.Pos()).Line,
  StatementSHA256:hex.EncodeToString(sum[:]),
  BodySHA256:hex.EncodeToString(whole[:]),
  ExtractionAssumptions:[]string{
   "The selected routeMethods.find HEAD branch is used for each native HEAD routing scenario",
   "No all-method fallback handler is registered by tested native scenarios",
   "The abstracted handlers have no route middlewares beyond the HEAD suppression test",
   "No whole Go evaluation or compiler correctness theorem is asserted",
  },
 }
 b,err:=json.MarshalIndent(receipt,"","  ");if err!=nil{panic(err)}
 if err=os.WriteFile(receiptPath,append(b,'\n'),0644);err!=nil{panic(err)}
 fmt.Println("P40_P6_ORIGINAL_AST_HEAD_BRANCH_GENERATION_PASS",receipt.StatementSHA256)
}
